# Generated by Django 5.0.6 on 2024-07-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_adopt_address_adopt_email_adopt_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopt',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adopt',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='adopt',
            name='full_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='adopt',
            name='phone_no',
            field=models.CharField(max_length=12),
        ),
    ]
