# Generated by Django 5.0.6 on 2024-08-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_alter_adopt_address_alter_adopt_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='review',
            field=models.TextField(default='No reviews yet.'),
        ),
    ]
