# Generated by Django 5.0.6 on 2024-08-02 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_pet_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
