# Generated by Django 5.0.6 on 2024-08-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0007_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='review',
            field=models.TextField(default='No review yet.'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
