# Generated by Django 5.0.6 on 2024-08-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0009_remove_pet_review_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author_email',
            field=models.CharField(default='a@gmail.com', max_length=50),
        ),
        migrations.AddField(
            model_name='review',
            name='author_username',
            field=models.CharField(default='abc', max_length=30),
        ),
    ]
