# Generated by Django 5.0.6 on 2024-08-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0010_review_author_email_review_author_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author_email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='author_username',
            field=models.CharField(max_length=30),
        ),
    ]
