# Generated by Django 5.0.6 on 2024-08-04 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0012_remove_pet_breed_remove_pet_color_remove_pet_sex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.breed'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.color'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.sex'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.size'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.species'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.status'),
        ),
    ]
