# Generated by Django 5.0.6 on 2024-08-04 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0013_alter_pet_breed_alter_pet_color_alter_pet_sex_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='color',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='size',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='species',
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pet.status'),
        ),
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.ManyToManyField(to='pet.breed'),
        ),
        migrations.AddField(
            model_name='pet',
            name='color',
            field=models.ManyToManyField(to='pet.color'),
        ),
        migrations.AddField(
            model_name='pet',
            name='sex',
            field=models.ManyToManyField(to='pet.sex'),
        ),
        migrations.AddField(
            model_name='pet',
            name='size',
            field=models.ManyToManyField(to='pet.size'),
        ),
        migrations.AddField(
            model_name='pet',
            name='species',
            field=models.ManyToManyField(to='pet.species'),
        ),
    ]
