# Generated by Django 5.0.6 on 2024-08-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0014_remove_pet_breed_remove_pet_color_remove_pet_sex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='picku/pet_image'),
        ),
    ]
