# Generated by Django 5.0.6 on 2024-08-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0022_alter_pet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='location',
            field=models.CharField(default='Dhaka', max_length=100),
        ),
    ]
