# Generated by Django 5.0.6 on 2024-08-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0023_pet_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
