# Generated by Django 5.0.6 on 2024-08-02 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_useraccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
