# Generated by Django 5.0.6 on 2024-08-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
